### ISSUE TITLE
Fix small bugs of the language translation

### ISSUE THREAD

**Issue by Miminiverse** [Talckatoo/talckatoo_client#164]
![image](https://github.com/Talckatoo/talckatoo_client/assets/109603295/5ad94a6c-d1c2-444c-9b94-33a33e1c9e87)
![image](https://github.com/Talckatoo/talckatoo_client/assets/109603295/ee7569b8-dc2a-4f74-95e1-327a7c32c151)

**Comment by TammamWafai** [comment]
@Miminiverse @Said-laasri Done!
