### ISSUE TITLE
Create landing Page for Talckatoo

### ISSUE THREAD

**Issue by Said-laasri** [Talckatoo/talckatoo_client#33]
https://www.figma.com/file/tvWJWYrJW9OgGaEPtxF6Ai/Talkato-Portfolio?type=design&node-id=0-1&mode=design&t=gXdNlGanlPYJarCm-0

Following Figma:

-Create a landing page
-Create routes for application  Sign/in/up
-Restyle  Sign UP page to match the design 
-Restyle  Sign IN page to match the design 

![Image](https://github.com/Talckatoo/talckatoo_client/assets/100702612/01f110aa-adf5-4fb0-a125-0223b9cda177)

![Image](https://github.com/Talckatoo/talckatoo_client/assets/100702612/948a0d01-4428-425c-8d6f-e2b44bf065ba)

**Comment by Miminiverse** [comment]
Done!!
